#!/bin/sh
# Applications
pgrep conky || conky &
# pidof clight || clight --lat=12.00 --lon=70.00 &
pidof redshift || redshift &
xrdb ~/.Xresources
# firefox &
# brave &
# mailsync &
# setxkbmap -layout 'us(colemak)',us -option grp:alt_shift_toggle &

~/.local/scripts/mpd_start &
pgrep bspswallow || ~/.local/scripts/bspwm/bspswallow &

xautolock -detectsleep -time 10 -locker lock.sh -notify 30 -notifier "notify-send -u critical -t 10000 -- 'LOCKING screen in 30 seconds'" &

# mate-power-manager &
